version: "3.3"

services:
  portfolio:
    image: timosur-portfolio
    environment:
      VIRTUAL_HOST: timosur.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: timosur.com
      LETSENCRYPT_EMAIL: dev@timosur.com
      NEXT_PUBLIC_COCKPIT_URL: https://cockpit.timosur.com
    restart: always
    expose:
      - 3000
    networks:
      - jwilder

networks:
  jwilder:
    external: 
      name: jwilder-proxy
