version: "3.3"

services:    
  portfolio:
    image: node:latest
    volumes:
      - ..:/usr/app
    environment: 
      - NEXT_PUBLIC_STRAPI_URL=https://strapi.timosur.com
    command: >
      bash -c "npm install
      && npm run dev"
    working_dir: /usr/app
    ports:
      - '1338:3000'
    network_mode: bridge