stages:
- deploy_web

on:
  push:
    branches:
      - 'master'

deploy_web:
  stage: build-deploy-web
  image: docker/compose:latest
  tags:
    - local-script
    - surcloud
  script:
    - chmod u+x build-run.sh
    - ./build-run.sh