name: build-deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy_web:
    runs-on: surcloud
    container:
      image: docker/compose:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod u+x build-run.sh
          ./build-run.sh