on:
  push:
    branches:
      - 'master'

jobs:
  deploy_web:
    image: docker/compose:latest
    tags:
      - local-script
      - surcloud
    steps:
      run: |
        chmod u+x build-run.sh
        ./build-run.sh